<p>A common core ideal of our modern societies has become productivity, being able to produce more in less time. We value a person being a productive member of society, we prefer technologies that allow us to produce more with less work. Although this is not necessarily a bad ideal, without other more human values to guide it we end up with our current state, where we produce for the sake of producing rather than to make our lives easier.</p>

<p>Despite the exponential improvement of technology (especially digital) over the past few decades our workload has not gotten thinner, and we find ourselves more stressed, depressed, and even lonely (despite the internet) than ever. The very same technology that we were told would make our lives easier and more leisurely has added more work onto our plates, despite the lack of actual need to produce so much. We keep ourselves constantly connected to our work through our mobile devices, and the time that once was for us to leave work, go home, and spend time with family, friends, and neighbors is now contaminated.</p>

<p>It's not as though we need such constant connection to the work place. To say that we need to be so productive, that such measures are necessary to sustain ourselves is simply a lie. For your average Joe there is very little need to be so productive (unless we consider using his labor to accommodate the lifestyle of another necessary). Ultimately it all comes down to a massive misuse of technology.</p>

<p>This becomes self-evident when we take a look at the controversy over automation. In any sane society where resources were managed properly, automation would be celebrated, as it would mean that we can work less (as it would no longer require so much work to produce the same amount). Instead of using this automation to allow people to work less hours and spend more time at home, the workers being replaced must now find another job where their man hours can be used to produce even more than before. But to what end?</p>

<p>I'm not suggesting that we use automation to abolish work entirely, work is what drives us, what gives us purpose, allowing us to come home and feel accomplished. Instead, I believe we should use this automation and increased productivity to produce the same, work less, spend more time at home with our loved ones, and improve our social, psychological, and physical health.</p>

