<p>Have you ever bought a new phone and seen that half its storage is already used up by apps you never wanted? Have you ever gotten a new computer and seen that the OS itself occupies 20-30GiB because it comes with a bunch of utilities and features you didn't ask for? If you run almost any UNIX, Linux, or BSD distribution your answer is "no". However, you probably know exactly what I'm talking about, and it's one of the reasons you don't use Google, Microsoft, or Apple products. In my case, I personally don't have this problem, but my grandparents do.</p>

<p>My grandparents have Android and MacOS devices, and the storage on these is always being filled. It's not because of photos and videos, because even though my Grandmother takes many whenever there is a family event she puts them all on Google servers (Google Photos or something). No, they are filled up to the brim with stupid apps that my grandparents will never use. The only apps my grandparents need are WhatsApp, <a href="https://wire.com/en/" target="_blank" >Wire</a>, phone, camera, browser, and the app to get the bus schedule. However, the phones they have come with a bunch of other applications that they will never use, such as: sports app, stock market app, PDF reader, document editor (which is stupid for a phone anyways), stupid mobile games they've never played, etc., and none of these can be uninstalled. All these extra apps on their devices do nothing more than to complicate their user experience, giving them a harder time managing their devices. At the end of the day, they come to me to solve their issues, and there's nothing I can do since I cannot uninstall the apps. I try to factory reset the apps (i.e. remove updates) which helps a little, but then the app store wants to update them.</p>

<p>So the question here is, why, for the love of God, do these companies put all this trash on our devices? Answer: politics and profits. OS development companies (especially mobile OS companies) tend to get revenue from contracts with app development companies so their apps are pre-installed on devices, and these contracts tend to include compensation for the OS development company. There is also the issue that <a href="https://www.statista.com/statistics/489255/percentage-of-us-smartphone-owners-by-age-group/" target="_blank" >smart phones are primarily used and purchased by youths</a>, who have an easier time managing resources and navigating new UIs on devices. This means that the primary demographic these companies are after aren't old people, who would be better suited with a simple UI, few apps, and consistency, but rather they are after the youths who prefer more features, new and shiny UIs, and a changing environment to keep things fresh. So in order to appeal to this younger audience, they treat the elderly horribly (the wonders of the free market, but that's a different topic).</p>

<p>I will recognize that there are mobiles you can buy that come with plain Android, which come only with certain Google apps installed by default, and are generally much more lightweight. However, there's a catch: they're more expensive. That's right, somehow you're paying more to have less crap on your device. What's more, you typically won't be able to buy these devices directly from your mobile/internet service provider, instead you'll have to buy it separately and set it up yourself (something that the elderly may have problems doing on their own).</p>

<p>After all this, it becomes quite clear that tech companies care very little for the elderly. Their primary market is the youth, and that's where they make their money; with kids who buy a new phone every 2 years for no good reason.</p>

<p>I'm pretty sure that many people have a similar situation with their parents/grandparents, and although I do not have a solution for mobile (if you know of a free software mobile OS with a simple and consistent UI, please go to my contact page and send me an e-mail) there is most definitely a solution for laptops and desktops: Linux. Although the installation isn't always easy (you should do this for them), using Linux can be extremely easy (considering the elderly mostly just use the web browser), especially if you know what desktop environment to install. If they are used to using Microsoft Windows, try using <a href="https://kde.org/" target="_blank" >KDE</a>. Otherwise, look into using DEs with a simple UI as well as a history without major changes, such as: <a href="https://cinnamon-spices.linuxmint.com/" target="_blank" >Cinnamon</a>, <a href="https://mate-desktop.org/" target="_blank" >MATE</a>, or <a href="https://xfce.org/" target="_blank" >Xfce</a>. If you're a GNOME fanboy, sorry, but GNOME doesn't make the cut since they had such a massive change to their UI paradigm going from GNOME 2 to GNOME 3. Also, use a distro known for stability and where you can easily automate updates. I've found that rolling release distros are a real help here, despite the supposed instability you get from running new software.</p>

