<p>Normally I dislike hopping onto bandwagons for this blog, but this is about a field that I am very involved in: the technology field. Recently a Google employee sent out an internal memo that later was published for the whole world to see (you can read the full memo <a href="https://diversitymemo.com/" target="_blank" >here</a>). This memo spawn much controversy, and so I wanted to see the memo itself.</p>

<p>Firstly I would like to bring up that the firing of this man is something that I consider completely unacceptable. People should not be fired for their personal opinions so long as they recognize that they are in a work environment and while at work only do so within the context of work (as this man has done). Otherwise we resort to the same kind of witch hunt that there was against Communists, Socialists, and Anarchists in the 50s.</p>

<p>After having read what was on the memo, I see no signs here of sexism, bigotry, anti-diversity, or anything of the sort. This man has respectfully and calmly proposed his suggestions as to why there are less women in the technology sector and (more importantly) how to fix it from within the limitations of Google. That is, he is not disagreeing on having more women in the technology sector, he simply disagrees on the causes and (by extension) the solutions. I believe that if this man were given a chance to have a rational conversation (which seems to be what he was looking for) rather than being insulted that he would have been very willing to listen to other people's opinions. This man has been very respectful and deserves the same respect in return, independently of how much you may disagree with his opinion.</p>

<p>As for my personal view on the matter, I am unsure of his biological arguments, however he seems to have linked to a few Wikipedia articles in his memo explaining this perspective on the matter. Despite this, I do believe that social pressure (on both women and men) has an affect on this matter. Women generally are not raised to have an interest in anything STEM (Science, Technology, Engineering, Mathematics), and therefore it is not surprising that there are less women in those fields. When I go to my Computer Engineering classes I see two girls in a class of about 60 people, yet the university is primarily an engineering university and tries very hard to get women into engineering. It's not that the university is discriminating against women, it's that these women were not raised to enjoy the abstract ideas, instead they were raised with dolls, make-up kits, art boxes, and so on, while their boy siblings were raised with Legos, science kits, handyman belts, and so on. Then, the fact that we do not raise boys with the other means that these 'girly' things end up being purely for girls, and therefore much easier to tie oneself to and identify with. Then, men are also never really introduced to arts and humanities and therefore end up dominating the STEM fields, while if they were exposed to them then they may end up taking more of the arts and humanities jobs.</p>

<p>The difference in proportion of women in STEM and men in arts and humanities is not something that can be solved at such a high level, not by companies like Google, and not by universities like my own. This is something that needs to be solved at a younger age by public schools and (most importantly) at home when raising children. What use does it make to have companies like Google make tech jobs more attractive for women when there aren't that many women even studying it in university? And what use does it make to have universities lower tuition for women in tech when not many women want to go into tech to begin with? The problem is much much deeper than these. Stop trying to blame administrators for being sexist and try looking at your own life and flaws. What are you training your daughter and son to like and enjoy doing? Why is your daughter going for a liberal arts degree while your son is going for a degree in civil engineering? Try fixing your own flaws and being consistent with your own ideas before trying to correct the behaviour of others. There are some minor inconsistencies that will always be there, but we must not stop trying to improve ourselves.</p>

