<?php
require 'config.php';
require '2016-08-20-my-loathing-of-apple.cfg.php';
require 'templates/blog-header.php';
?>
<p>I hate Apple, and I've had many bad experiences with them. Aside from how they are spying on you <a href="https://en.wikipedia.org/wiki/PRISM_%28surveillance_program%29" target="_blank" >being part of PRISM</a>, in general they are impossible with anyone who wants to use their products in combination with anyone else's. Let me explain my experiences that I have had with Apple.</p>

<p>For the first 15 years of my life I was an Apple user, using iPods, iPads, iMacs, and iStuff in general. I was exposed to stuff like GNU/Linux at school (because the Spanish school system actually uses ethical software, sadly only because they can't afford proprietary stuff, but whatever), especially with Debian GNU/Linux because that's what my dad ran for work, but I still used mostly Apple products. However, at 15 I got my first personal laptop, which was a Dell Inspiron something or another, all I remember is it was a 32-bit with 1GB of RAM, so obviously I installed GNU/Linux on it, specifically Debian GNU/Linux (at the time I had stable since my dad was the one helping me to install it). So I had my own computer, but my music player was still an iPod... Why was this a problem? Because iPods didn't want to sync with anything that wasn't iTunes. I had to do something like using my family's Apple Mac (non-free software) to turn off the journaling on that thing and then every now and then I had to do it again because the iPod noticed!!! Unlike some other music players where I can <b>drag and drop my files</b>.</p>

<p>That was not the only issue, but it was the first. After that I started realizing how my family (except my dad) who all used Apple applications could not communicate with <b>anything</b> of mine. Imagine being isolated (technologically) because you use a less shiny piece of hardware that costs significantly less. That's exactly how it was with me and my family. So I continued to hate it, especially when I went to school with my laptop and the school (who used Apple) gave me files <b>that were Apple specific!</b> Bad move for a <b>public school</b>. And so these events continued as I couldn't cooperate on anything because of 'muh iStuff'. It got to the point where I basically refused to use anything Apple, and it didn't help that one year the school starting giving all the students iPads. At least this time they were thinking "What if a student's computer can't run our software on it?" as compared to the previous times where they basically said "we don't care about you." But even then, what about my freedom? Ignoring my principles of free software which I had at the time. I basically left that machine at my house and never brought it to school in order to prove a point. Every time they said to do something on the iPad I would do it on my machine using free software.</p>

<p>So, that's how I left the realm of Apple, but once I was out I was glad to have left. Looking from the outside in all I see is mindless zombies fighting over <b>a phone!!!</b> I swear, Apple fanboys are the worst along with bronies. There is no reason for you to get the phone a week before everyone else for a higher price. Just let all the other idiots get the expensive one a week earlier while you (the 'smart' one) waits patiently until the price goes down... to about half a fortune instead of an entire one. Seriously, you get <b>nothing</b> out of Apple products that you can't get out of others for <b>much</b> less money. But of course, we all need to show off how much money we have (or, how much money we can suck out of our working class parents) to pay for a phone that does the same thing as the other one that costs 70% less. But Apple has some way of convincing their fanboys that their iStuff is special and better than everyone else's because it has a logo of an apple with a bite taken out of it on the back. So you're saying I can tattoo an apple to my nuts and these fanboys will start obsessing over it? Also, just because I'm saying fanboys doesn't mean this doesn't apply to women, or even men that are older. Heck, from what I've seen Apple has two main markets, teenagers who act like hipsters and adults in their mid-life crisis who are already throwing money everywhere (also, a lot of old people have Apple, not because they bought it themselves, but rather because their children who are in their mid-life crisis bought it for them, they really don't care themselves).</p>

<p>Worst is with my poor grandparents, one of their children (you know who you are) bought them an iPad and a Macbook, but the poor souls don't know any better, so now they don't know that if they want to hold on to those family photos better continue to buy expensive Apple products when that breaks. I'm still waiting for something to break so I can intervene first and have them use free software, it also helps that I'm physically closer to them than 'that family member' is. The day will come... just hope it arrives a little faster (-_-). Soon they'll be saying "Bye bye Apple, hello Debian!" (no way I would install Ubuntu considering that even they have done some shady stuff recently).</p>

<p>So now you know my story. I <b>hate</b> Apple, I hate them even more than I hate Microsoft and their nonsense, in the case of Apple it's just personal. So if you ever know me, or already do and never knew this, <b>don't get me anything Apple</b>. It might be harsh but I would probably end up either asking you for the receipt or at the very most saying thank you and then stashing it somewhere in <b>someone else's</b> house where it can't track me (PRISM). Speaking of gifts, if you're reading this and wondering what to get me now that you can't buy me the latest iStuff, please refer back to my blog post on <a href="/blog/post/50/" >Ethical Giving</a> which uses the FSF's guide to finding an ethical technological gift for someone.</p>


<?php
require 'templates/blog-footer.php';
?>