<?php
require 'config.php';
require '2016-07-04-game-website-app-creators.cfg.php';
require 'templates/blog-header.php';
?>
<p>A topic that I am very disturbed about are Game/Website creators. These
programs are what I consider is helping to destroy the technology industry.
Not only is this causing for more people to be able to create mediocre apps
(games, websites, or otherwise) and therefore lowering programming salaries
and the chances <b>real programmers</b> have of obtaining a job, but it also
promotes bad code leading to bloated projects.</p>

<p>The first aspect is that these 'creators' are destroying the industry for
<b>real programmers</b> (not people who think they're programmers because
some mobile app creator helped them make a stupid clock app that they put
on their phone). This is because it is allowing more people who have <b>no
respect</b> for the field to enter and create bad apps. More people
entering the field means less work for <b>real programmers</b> and the little
work that may be found will be for lower wages (something that for now the
programmer master race has been able to avoid because of the few people
who want to get involved in programming due to its intense logic and, in
some cases, mathematics).</p>

<p>The second aspect is that it leads to bad code and terrible performance.
This is because these creators turn whatever is put into their GUI into a
real programming language which then gets compiled or interpreted. The
issue with this kind of cross-compiling is that it makes the code <b>a lot</b>
uglier and <b>a lot</b> messier. A good example of this without even looking
at creators is the <a href="http://haxe.org/" target="_blank" >HaXe Programming Language</a>, which I
had used for a while to make Flash games (before thinking I'm stupid for
using Flash please take into account that this was before JavaScript became
such a powerful language that you could easily write games with it, before
HTML5 came out). With HaXe you don't actually compile, you cross-compile
into another language and that language then gets compiled or interpreted.
Now, if you look at the code that is generated by HaXe in the other
language (as I have) you will see that it is <b>very</b> unnecessarily messy.
This isn't hard to understand why it creates something so messy, just think
how you would actually do something like this, that cross-compiles to
another language, it's not a very easy task. Same goes for the creators,
they turn whatever you created in the GUI to a programming language and
along with it comes a ton of unnecessary code that will just take up more
memory and make performance slower. In this aspect, can I blame them? No.
But that doesn't justify it being a replacement for the programming the
app yourself.</p>

<p>Finally, even though one could say "It helps others get interested in the
field.". This is wrong, very much so. How can one say that it will help
others gain interest in the field if they're not even doing anything about
the field (that is, <b>they're not programming</b>). If you're using a creator
you obviously don't care about the field, since you're trying very hard to
avoid all the hard stuff that goes along with creating decent apps. Instead
of learning it all, hard and easy, you learn something that does the actual
programming for you ('game maker make me a game') instead of having genuine
interest in making something nice.</p>

<p>To put it this way, I'm fine if you use a website creator, for example, to
make a personal website of yours (just don't expect me to debug it
when things to wrong, 'cause I don't want to have to go through one <b>very
long line</b> of HTML and CSS). Other than that, <b>no game creators</b> and
<b>no app creators</b>. All these do is ruin the the programming industry and
turn code quality down, performance down, and wages down.</p>


<?php
require 'templates/blog-footer.php';
?>