<?php
require 'config.php';
require '2019-07-31-the-honorable-sacrifice-of-ones-soul.cfg.php';
require 'templates/blog-header.php';
?>
<p>Almost every developed civilization has seen killing as unethical, especially when killing someone within one's own tribe. This is for the obvious reason that killing members of your own community harms your community's chances of survival since you have one less member and (in the case of fertile or young community members) harms your community's future (especially if the victim is a woman). However, there have always been times when this rule has been ignored even within the community, primarily as a way of removing undesirables who live only to cause the community harm via the death penalty.</p>

<p>In the modern era we seem to have a kind of schizophrenia with regards to this issue. On the one hand we have our civil society, which teaches that all human lives are equal and no one has the right to end the life of another. The problem with this idea is that it's based on the notion of individualism: that no matter what an individual does to harm the community, no one has the right to harm said individual (even to prevent future harm to others). On the other hand, we have the military of our societies which dehumanizes the enemy, painting them as pure evil and therefore a justified kill (even though many innocents are often stuck in the cross-fire). This leans more towards authoritarian ideals where all that matters is the word of the commanding officer, and all who oppose are not human.</p>

<p>This schizophrenia on the issue of killing is also present in other crimes, such as theft and torture. There is no unified code of ethics for both these parts of our world, they are contradictory in their teachings and neither seems to be able to respond to reality. The civil society understands that all human life has value, but fails to recognize that there are instances where our code of ethics must be broken. The military understands that there is a greater cause to fight for, but doesn't recognize the value of human life. So what's missing?</p>

<p>Put quite simply, our civil society is missing the notion of sacrifice and the military is lacking the notion of responsibility. The civil society doesn't understand that there are times where we must sacrifice of ourselves for the greater good, and the military doesn't understand that it must take responsibility for the lives it ends. In effect, what both these are missing is the concept of sacrificing one's soul for the greater good. Although we must recognize that every human life has equal ethical value, and no killing can be ethically justified (with the exception of self-defense), there comes a time when every man must be willing to sacrifice his life and soul for the survival of his own community.</p>

<p>Although I personally do not believe in the soul, nor the realms of heaven and hell, I think that for this it is important to think as though there were real. If you commit a crime for the well-being of your community you are not free from judgement, and your crime is by no means ethical (even if it is dismissed/ignored by those you had done it for), and in a sense your soul is still damned to hell. However, this sacrifice of one's soul for the collective good is important and should be applauded (when truly done for the well-being of the community) but the individual who committed the crime should also understand that they have done something horrible which can never be forgiven. Viewing this as a sort of trade gives each of us individually a way of understanding when we are willing to commit a crime for others, while making sure we understand that no matter who we're doing it for, no matter the motive, it is ultimately an evil act that we are committing.</p>

<p>With this we finally have both sacrifice and responsibility in the same basket. The person who commits a crime for the good of others will recognize that sooner or later they must pay for their crimes, but if they believe that the well-being of their loved ones is more important than the price they will have to pay for the crime, then although their actions may be wrong, they are undoubtedly honorable.</p>


<?php
require 'templates/blog-footer.php';
?>